Repository anup-a/svgwave, pull requests merged in 2021-10, with the labels that each got.

#31 Animated wave
  src/components/customBar.jsx
  src/components/home.jsx
  src/core/bezier-spline.js
  src/core/index.js
  src/core/wave.js
  src/index.html
Labels: hacktoberfest

#44 add github star
  package.json
  src/components/nav.jsx
Labels: hacktoberfest

#43 Use Zustand for state managment
  package.json
  src/App.jsx
  src/components/gradientPicker.jsx
  src/hooks/useDarkMode.js
  src/stores/useDarkMode.js
  src/styles/main.css
  yarn.lock
Labels: hacktoberfest-accepted

#45 Add gradient angle slider inside the gradient color picker window
  src/components/colorTool.jsx
  src/components/customBar.jsx
  src/components/gradientPicker.jsx
  src/components/home.jsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberest-accepted, hacktober-fest
